version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    restart: always
    ports:
      - "8000:80"
    environment:
      APP_ENV: production
      APP_DEBUG: true
      DB_CONNECTION: pgsql
      DB_HOST: dpg-cvk2plruibrs739sj38g-a
      DB_PORT: 5432
      DB_DATABASE: pruebarender_db
      DB_USERNAME: pruebarender_db_user
      DB_PASSWORD: ""
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: laravel_db
    restart: always
    environment:
      POSTGRES_DB: pruebarender_db
      POSTGRES_USER: pruebarender_db_user
      POSTGRES_PASSWORD: ""
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
